FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /adminka


RUN pip install --upgrade pip

COPY ./requirements.txt /adminka
COPY ./entrypoint.sh /adminka

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /adminka

ENTRYPOINT ["/adminka/entrypoint.sh"]

