version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty19ytrewq
      - POSTGRES_DB=db

  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
    restart: always
    volumes:
      - ./storage/redis/data:/data

  management:
    build:
        context: adminka
        dockerfile: DockerFile
    command: python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - ./adminka/.env
    depends_on:
      - db


  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    depends_on:
      - db
      - redis

